services:
  hvcd-app:
    container_name: 'hvcd-app'
    command: npm run start:debug
    build:
      context: .
      dockerfile: ./local.Dockerfile
      target: dev
    ports:
      - ${PORT}:${PORT}
      - 7777:7777
    volumes:
      - .:/usr/hvcd-app
      - ./secrets-dev:/usr/hvcd-app/secrets
      - /usr/hvcd-app/node_modules
    depends_on:
      - mongo
      # - redis
    tty: true
    environment:
      - PORT=${PORT}
  mongo:
    container_name: 'hvcd-mongo'
    image: mongo:7.0.5
    volumes:
      - ./init-mongo/entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js:ro
    command: --port ${MONGODB_PORT}
    environment:
      - MONGODB_PORT=${MONGODB_PORT}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
